/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iuEscritorio;

import controlador.ControladorAsignarBonificacion;
import controlador.VistaAsignarBonificacion;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Bonificacion;
import logica.BonificacionAsignada;
import logica.Puesto;
import logica.Tarifa;
import logica.UsuarioPropietario;

/**
 *
 * @author sebastianlb
 */
public class AsignarBonificacion extends javax.swing.JDialog implements VistaAsignarBonificacion {

    /**
     * Creates new form AsignarBonificacion
     */
    private ControladorAsignarBonificacion controlador;
    public AsignarBonificacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controlador = new ControladorAsignarBonificacion(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBonificaciones = new javax.swing.JLabel();
        lblPuestos = new javax.swing.JLabel();
        lblPuestos1 = new javax.swing.JLabel();
        tfCedula = new javax.swing.JTextField();
        cbPuestos = new javax.swing.JComboBox();
        cbBonificaciones = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblPropietario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBonificaciones = new javax.swing.JTable();
        btnAsignar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBonificaciones.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblBonificaciones.setText("Bonificaciones:");

        lblPuestos.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPuestos.setText("Puestos:");

        lblPuestos1.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblPuestos1.setText("Cedula:");

        tfCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCedulaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblPropietario.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPropietario.setText("propietario");

        jScrollPane1.setViewportView(tablaBonificaciones);

        btnAsignar.setText("Asignar");

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblBonificaciones)
                        .addGap(18, 18, 18)
                        .addComponent(cbBonificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblPuestos)
                        .addGap(18, 18, 18)
                        .addComponent(cbPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lblPuestos1)
                        .addGap(18, 18, 18)
                        .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPropietario)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBonificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBonificaciones))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblPuestos))
                    .addComponent(cbPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblPuestos1))
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPropietario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAsignar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnCerrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCedulaActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        controlador.buscarPropietario(tfCedula.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JComboBox cbBonificaciones;
    private javax.swing.JComboBox cbPuestos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBonificaciones;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblPuestos;
    private javax.swing.JLabel lblPuestos1;
    private javax.swing.JTable tablaBonificaciones;
    private javax.swing.JTextField tfCedula;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarBonificaciones(ArrayList<Bonificacion> bonificaciones) {
        cbBonificaciones.removeAllItems();
        for (Bonificacion b : bonificaciones) {
            cbBonificaciones.addItem(b);
        }
    }

    @Override
    public void cargarPuestos(ArrayList<Puesto> puestos) {
        cbPuestos.removeAllItems();
        for (Puesto p : puestos) {
            cbPuestos.addItem(p);
        }
    }

    @Override
    public void mostrarDatosPropietario(UsuarioPropietario usuario,ArrayList<BonificacionAsignada> bonificacionesAsigndas) {
        lblPropietario.setText(usuario.getNombreCompleto());
        DefaultTableModel datos = new DefaultTableModel();
        datos.addColumn("Bonificacion");
        datos.addColumn("Puesto");

        datos.setRowCount(bonificacionesAsigndas.size());
        int fila = 0;
        for(BonificacionAsignada ba:bonificacionesAsigndas){
            datos.setValueAt(ba.getBonificacion().getNombre(), fila, 0);
            datos.setValueAt(ba.getPuesto().getNombre(), fila, 1);

            fila++;
       }
       tablaBonificaciones.setModel(datos);
    }

   @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message,"Error",JOptionPane.ERROR_MESSAGE);
    }
    
    @Override
    public void exito(String message) {
        JOptionPane.showMessageDialog(this, message,"Exito",JOptionPane.INFORMATION_MESSAGE);
    }
}
