/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iuEscritorio;

import logica.Conexion;
import logica.Fachada;
import logica.UsuarioAdministrador;

/**
 *
 * @author sebastianlb
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    private Conexion conexion;
    private UsuarioAdministrador usr;
    public MenuAdministrador(UsuarioAdministrador usr) {
        initComponents();
        this.usr = usr;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        itemEmularTransito = new javax.swing.JMenu();
        itemAprobarRecarga = new javax.swing.JMenu();
        itemAsignarBonificacion = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MENU ADMINISTRADOR");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        itemEmularTransito.setText("Emular Transito");
        itemEmularTransito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemEmularTransitoMouseClicked(evt);
            }
        });
        itemEmularTransito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmularTransitoActionPerformed(evt);
            }
        });
        jMenuBar1.add(itemEmularTransito);

        itemAprobarRecarga.setText("Aprobar Recarga");
        itemAprobarRecarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAprobarRecargaMouseClicked(evt);
            }
        });
        itemAprobarRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAprobarRecargaActionPerformed(evt);
            }
        });
        jMenuBar1.add(itemAprobarRecarga);

        itemAsignarBonificacion.setText("Asignar Bonificacion");
        itemAsignarBonificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAsignarBonificacionMouseClicked(evt);
            }
        });
        itemAsignarBonificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAsignarBonificacionActionPerformed(evt);
            }
        });
        jMenuBar1.add(itemAsignarBonificacion);

        itemSalir.setText("Salir");
        itemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemSalirMouseClicked(evt);
            }
        });
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(itemSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salir(){
         Fachada.getInstancia().logout(conexion);
         this.dispose();
    }
    
    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
       salir();
    }//GEN-LAST:event_itemSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         salir();
    }//GEN-LAST:event_formWindowClosing

    private void itemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSalirMouseClicked
        // TODO add your handling code here:
       salir();
    }//GEN-LAST:event_itemSalirMouseClicked

    private void itemEmularTransitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmularTransitoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itemEmularTransitoActionPerformed

    private void itemEmularTransitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemEmularTransitoMouseClicked
        // TODO add your handling code here:
        new EmularTransito(this,false).setVisible(true);
    }//GEN-LAST:event_itemEmularTransitoMouseClicked

    private void itemAsignarBonificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAsignarBonificacionActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itemAsignarBonificacionActionPerformed

    private void itemAsignarBonificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAsignarBonificacionMouseClicked
        // TODO add your handling code here:
        new AsignarBonificacion(this, false).setVisible(true);
    }//GEN-LAST:event_itemAsignarBonificacionMouseClicked

    private void itemAprobarRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAprobarRecargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAprobarRecargaActionPerformed

    private void itemAprobarRecargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAprobarRecargaMouseClicked
        // TODO add your handling code here:
        new ConfirmarRecarga(usr).setVisible(true);
    }//GEN-LAST:event_itemAprobarRecargaMouseClicked

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemAprobarRecarga;
    private javax.swing.JMenu itemAsignarBonificacion;
    private javax.swing.JMenu itemEmularTransito;
    private javax.swing.JMenu itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
