/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iuEscritorio;

import Exceptions.NumeroNegativoException;
import controlador.ControladorRecargarSaldo;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Fachada;
import logica.Recarga;
import logica.Recarga.EstadoRec;
import logica.UsuarioPropietario;
import observador.Observable;
import observador.Observador;
import controlador.VistaRecargarSaldo;

/**
 *
 * @author rodri
 */
public class RecargarSaldo extends javax.swing.JFrame implements VistaRecargarSaldo {
    private UsuarioPropietario usuario;
    
    /**
     * Creates new form RecargarSaldo
     */
    
    private ControladorRecargarSaldo controlador;
    
    public RecargarSaldo(UsuarioPropietario usr) {
        initComponents();
        this.usuario = usr;
        this.controlador = new ControladorRecargarSaldo(this,usr);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNomUsuario = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        lSaldoUsuario1 = new javax.swing.JLabel();
        lMonto = new javax.swing.JLabel();
        tMontoARecargar = new javax.swing.JTextField();
        btnRecargar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lNomUsuario.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lNomUsuario.setForeground(new java.awt.Color(0, 0, 0));
        lNomUsuario.setText("nombre usuario");

        l1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(84, 130, 53));
        l1.setText("$");

        lSaldoUsuario1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lSaldoUsuario1.setForeground(new java.awt.Color(84, 130, 53));
        lSaldoUsuario1.setText("saldo usuario");

        lMonto.setText("Monto a recargar :");

        btnRecargar.setText("Aceptar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tMontoARecargar, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(l1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lSaldoUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNomUsuario)))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(lNomUsuario)
                    .addComponent(lSaldoUsuario1))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMonto)
                    .addComponent(tMontoARecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnRecargar)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
// TODO add your handling code here:
    recargarSaldo();
        
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        //recarga.quitarObservador(this);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecargarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel lMonto;
    private javax.swing.JLabel lNomUsuario;
    private javax.swing.JLabel lSaldoUsuario1;
    private javax.swing.JTextField tMontoARecargar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarDatosUsuario(UsuarioPropietario usr) {
        lNomUsuario.setText(usr.getNombreCompleto());
        lSaldoUsuario1.setText(String.valueOf(usr.getSaldo()));
    }
    
     @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message,"Error",JOptionPane.ERROR_MESSAGE);
    }
    
    @Override
    public void exito(String message) {
        JOptionPane.showMessageDialog(this, message,"Exito",JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
    }

    @Override
    public void recargarSaldo() {
        double monto = Double.parseDouble(tMontoARecargar.getText());
         controlador.recargarSaldo(monto);
    }

  
    
}
