/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package iuEscritorio;

import controlador.ControladorTransitoExitoso;
import controlador.VistaTransitoExitoso;
import java.beans.Visibility;
import logica.Transito;

/**
 *
 * @author sebastianlb
 */
public class TransitoExitoso extends javax.swing.JDialog implements VistaTransitoExitoso{

    /**
     * Creates new form TransitoExitoso
     */
    private ControladorTransitoExitoso controlador;
    public TransitoExitoso(java.awt.Frame parent, boolean modal,Transito t) {
        super(parent, modal);
        initComponents();
        this.controlador= new ControladorTransitoExitoso(this,t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPropietario = new javax.swing.JLabel();
        lblNombrePropietarioValue = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        lblCategoriaValue = new javax.swing.JLabel();
        lblCosto = new javax.swing.JLabel();
        lblCostoValue = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblSaldoValue = new javax.swing.JLabel();
        lblBonificacion = new javax.swing.JLabel();
        lblBonificacionValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblPropietario.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblPropietario.setText("Propietario:");

        lblNombrePropietarioValue.setText("nombreProp");

        lblCategoria.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria:");

        lblCategoriaValue.setText("categoria");

        lblCosto.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblCosto.setText("Costo:");

        lblCostoValue.setText("costo");

        lblSaldo.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblSaldo.setText("Saldo Final:");

        lblSaldoValue.setText("saldo");

        lblBonificacion.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblBonificacion.setText("Bonificacion:");

        lblBonificacionValue.setText("bonificacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBonificacion)
                    .addComponent(lblPropietario)
                    .addComponent(lblCategoria)
                    .addComponent(lblCosto)
                    .addComponent(lblSaldo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombrePropietarioValue)
                    .addComponent(lblCategoriaValue)
                    .addComponent(lblCostoValue)
                    .addComponent(lblSaldoValue)
                    .addComponent(lblBonificacionValue))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPropietario)
                    .addComponent(lblNombrePropietarioValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(lblCategoriaValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCosto)
                    .addComponent(lblCostoValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldo)
                    .addComponent(lblSaldoValue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBonificacion)
                    .addComponent(lblBonificacionValue))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBonificacion;
    private javax.swing.JLabel lblBonificacionValue;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCategoriaValue;
    private javax.swing.JLabel lblCosto;
    private javax.swing.JLabel lblCostoValue;
    private javax.swing.JLabel lblNombrePropietarioValue;
    private javax.swing.JLabel lblPropietario;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblSaldoValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarDatosTransito(Transito t) {
        lblNombrePropietarioValue.setText(t.getVehiculo().getPropietario().getNombreCompleto());
        lblCategoriaValue.setText(t.getVehiculo().getCategoria().getNombre());
        lblCostoValue.setText(""+t.getMontoPagado());
        lblSaldoValue.setText(""+t.getVehiculo().getPropietario().getSaldo());
        
        if(t.getBonificacion() != null){
            lblBonificacion.setVisible(true);
            lblBonificacionValue.setText(t.getBonificacion().getBonificacion().getNombre());
        }else{
            lblBonificacion.setVisible(false);
            lblBonificacionValue.setText("");
        }
    }
}
